"""
Generic repository interface for the AutoForge AI platform.

Defines the abstract base class ``Repository`` that all concrete repository
implementations must extend. The interface is fully generic over the entity
type and uses standard Python ABC + generics.

This module defines **contracts only**. No storage technology is imported
or referenced.
"""

from __future__ import annotations

import uuid
from abc import ABC, abstractmethod
from typing import (
    Any,
    AsyncIterator,
    Generic,
    Sequence,
    TypeVar,
)

from autoforge_models.base import AutoForgeBaseModel

T = TypeVar("T", bound=AutoForgeBaseModel)


class Repository(ABC, Generic[T]):
    """
    Abstract base class for all repositories in the AutoForge AI platform.

    Provides a technology-agnostic interface for CRUD operations on
    domain entities. Concrete implementations must provide the actual
    storage logic (e.g. SQL, NoSQL, in-memory for testing).

    Type parameter ``T`` is the domain model class this repository manages.
    It must be a subclass of ``AutoForgeBaseModel``.

    All methods are asynchronous to support non-blocking I/O in production
    storage backends.
    """

    @abstractmethod
    async def get(self, id: uuid.UUID) -> T:
        """
        Retrieve a single entity by its unique identifier.

        Args:
            id: The UUID of the entity to retrieve.

        Returns:
            The entity instance.

        Raises:
            EntityNotFoundError: If no entity with the given ``id`` exists.
        """
        ...

    @abstractmethod
    async def list(
        self,
        *,
        skip: int = 0,
        limit: int = 100,
        **filters: Any,
    ) -> Sequence[T]:
        """
        List entities with optional pagination and filtering.

        Args:
            skip: Number of records to skip (for pagination).
            limit: Maximum number of records to return.
            **filters: Keyword arguments used to filter results. The exact
                filtering semantics are implementation-defined.

        Returns:
            A sequence of entity instances matching the criteria.
        """
        ...

    @abstractmethod
    async def add(self, entity: T) -> T:
        """
        Persist a new entity.

        Args:
            entity: The entity instance to persist. The ``id`` field may
                be generated by the implementation if not already set.

        Returns:
            The persisted entity, including any generated state (e.g. ``id``,
            ``created_at``, ``updated_at``).

        Raises:
            DuplicateEntityError: If an entity with the same unique
                identifier already exists.
        """
        ...

    @abstractmethod
    async def update(self, entity: T) -> T:
        """
        Update an existing entity.

        Args:
            entity: The entity instance containing the updated fields.
                The ``id`` field must identify an existing record.

        Returns:
            The updated entity as persisted.

        Raises:
            EntityNotFoundError: If no entity with the given ``id`` exists.
            ConcurrencyError: If a concurrent modification is detected.
        """
        ...

    @abstractmethod
    async def remove(self, id: uuid.UUID) -> None:
        """
        Delete an entity by its unique identifier.

        Args:
            id: The UUID of the entity to delete.

        Raises:
            EntityNotFoundError: If no entity with the given ``id`` exists.
        """
        ...

    @abstractmethod
    async def exists(self, id: uuid.UUID) -> bool:
        """
        Check whether an entity with the given identifier exists.

        Args:
            id: The UUID to check.

        Returns:
            ``True`` if the entity exists, ``False`` otherwise.
        """
        ...


class AsyncIterableRepository(Repository[T], ABC, Generic[T]):
    """
    Extension of ``Repository`` that supports async iteration.

    Repositories that back large collections may benefit from providing
    an async iterator over all entities, enabling memory-efficient
    streaming of results without loading the entire dataset at once.
    """

    @abstractmethod
    async def __aiter__(self) -> AsyncIterator[T]:
        """
        Iterate over all entities asynchronously.

        Yields:
            Entity instances one at a time.
        """
        ...
        yield  # pragma: no cover